const API = 'http://localhost:8080/api';
let token = localStorage.getItem('museum_token');
let authMode = 'login';
let selectedDate = new Date();
const $ = s => document.querySelector(s);
const request = async (path, options = {}) => { const headers = {'Content-Type':'application/json', ...(options.headers||{})}; if(token) headers.Authorization = `Bearer ${token}`; const res = await fetch(API + path, {...options, headers}); const data = await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.message || '请求失败'); return data; };
function dates(){const strip=$('#dateStrip'); strip.innerHTML=''; for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()+i);const el=document.createElement('button');el.className='date-card'+(d.toDateString()===selectedDate.toDateString()?' active':'');el.innerHTML=`<small>${['日','一','二','三','四','五','六'][d.getDay()]}曜日</small><strong>${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}</strong>`;el.onclick=()=>{selectedDate=d;dates();loadAvailability()};strip.appendChild(el)}}
async function loadAvailability(){const iso=selectedDate.toISOString().slice(0,10);try{const days=await request(`/ticketing/availability?from=${iso}&to=${iso}`);const day=days[0];$('#availability').innerHTML=day?day.slots.map(s=>`<article class="slot-card"><div class="slot-time"><strong>${s.slotCode}</strong><span>${s.checkinStart.slice(0,5)} — ${s.checkinEnd.slice(0,5)}</span></div><div class="ticket-pills">${s.tickets.map(t=>`<div class="ticket ${t.availableQuantity<1?'sold':''}">${t.name}<b>¥${t.price} · ${t.availableQuantity}张</b></div>`).join('')}</div><span class="order-status">${s.tickets.some(t=>t.availableQuantity>0)?'可预约':'已售罄'}</span></article>`).join(''):'<div class="empty-state">当天暂无开放场次，请选择其他日期。</div>'}catch(e){$('#availability').innerHTML=`<div class="empty-state">暂时无法读取场次：${e.message}</div>`}}
async function loadPeople(){if(!token)return;try{const people=await request('/real-persons');$('#peopleList').innerHTML=people.length?people.map(p=>`<div class="person-row"><div><strong>${p.name}</strong><small>${p.idType} · ${p.idMasked}${p.isSelf?' · 本人':''}</small></div></div>`).join(''):'<div class="empty-state">还没有实名人员。</div>'}catch(e){$('#peopleList').innerHTML='<div class="empty-state">登录后查看实名人员</div>'}}
async function loadOrders(){if(!token)return;try{const orders=await request('/orders');$('#ordersList').innerHTML=orders.length?orders.map(o=>`<div class="order-row"><div><strong>${o.visitDate}</strong><small>${o.orderId} · ${o.details.length} 张 · ¥${o.price}</small></div><span class="order-status">${o.status}</span></div>`).join(''):'<div class="empty-state">还没有预约记录。</div>'}catch(e){}}
function openAuth(){ $('#authDialog').showModal(); $('#authError').textContent=''; $('#authTitle').textContent=authMode==='login'?'游客登录':'创建游客账号'; $('#authSubmit').firstChild.textContent=authMode==='login'?'登录 ':'注册 '; }
$('#loginButton').onclick=()=>token? (localStorage.removeItem('museum_token'),token=null,location.reload()):openAuth(); $('#switchAuth').onclick=()=>{authMode=authMode==='login'?'register':'login';openAuth()}; $('#authForm').onsubmit=async e=>{e.preventDefault();try{const body={mobile:$('#mobile').value,password:$('#password').value};const data=await request(`/auth/${authMode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(body)});if(authMode==='login'){token=data.token;localStorage.setItem('museum_token',token)}else{authMode='login';token=null}$('#authDialog').close();$('#loginButton').textContent='退出登录';loadPeople();loadOrders()}catch(err){$('#authError').textContent=err.message}}; $('#refreshOrders').onclick=loadOrders; $('#prevDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);if(selectedDate<new Date())selectedDate=new Date();dates();loadAvailability()}; $('#nextDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);dates();loadAvailability()};
dates();loadAvailability();if(token){$('#loginButton').textContent='退出登录';loadPeople();loadOrders()}
