const API='http://localhost:8080/api';let token=localStorage.getItem('museum_token'),authMode='login',selectedDate=new Date(),people=[],chosenTicket;const $=s=>document.querySelector(s);
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(API+path,{...options,headers}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'请求失败');return data}
function needLogin(){if(token)return true;$('#authDialog').showModal();return false}
function renderDates(){const strip=$('#dateStrip');strip.innerHTML='';for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()+i);const b=document.createElement('button');b.className='date-card'+(d.toDateString()===selectedDate.toDateString()?' active':'');b.innerHTML=`<small>${['日','一','二','三','四','五','六'][d.getDay()]}曜日</small><strong>${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}</strong>`;b.onclick=()=>{selectedDate=d;renderDates();loadAvailability()};strip.appendChild(b)}}
async function loadAvailability(){const iso=selectedDate.toISOString().slice(0,10);try{const day=(await request(`/ticketing/availability?from=${iso}&to=${iso}`))[0];$('#availability').innerHTML=day?day.slots.map(s=>`<article class="slot-card"><div class="slot-time"><strong>${s.slotCode}</strong><span>${s.checkinStart.slice(0,5)} — ${s.checkinEnd.slice(0,5)}</span></div><div class="ticket-pills">${s.tickets.map((t,i)=>`<button class="ticket ${t.availableQuantity<1?'sold':''}" ${t.availableQuantity<1?'disabled':''} data-stock="${t.stockId}" data-slot="${s.slotCode}" data-name="${t.name}" data-price="${t.price}">${t.name}<b>¥${t.price} · ${t.availableQuantity}张</b></button>`).join('')}</div><span class="order-status">选择票种预约</span></article>`).join(''):'<div class="empty-state">当天暂无开放场次。</div>';document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>openBooking({stockId:b.dataset.stock,name:b.dataset.name,price:b.dataset.price,slotCode:b.dataset.slot}))}catch(e){$('#availability').innerHTML=`<div class="empty-state">读取失败：${e.message}</div>`}}
async function loadPeople(){if(!token)return;people=await request('/real-persons');$('#peopleList').innerHTML=people.length?people.map(p=>`<div class="person-row"><div><strong>${p.name}</strong><small>${p.idType} · ${p.idMasked}${p.isSelf?' · 本人':''}</small></div></div>`).join(''):'<div class="empty-state">还没有实名人员。</div>'}
async function loadOrders(){if(!token)return;const orders=await request('/orders');$('#ordersList').innerHTML=orders.length?orders.map(o=>`<div class="order-row"><div><strong>${o.visitDate}</strong><small>${o.orderId} · ${o.details.length}张 · ¥${o.price}</small></div><div class="order-actions"><span class="order-status">${o.status}</span>${o.status==='待支付'?`<button class="mini-button" data-pay="${o.orderId}">支付</button><button class="mini-button" data-cancel="${o.orderId}">取消</button>`:''}${o.status==='已支付'?`<button class="mini-button" data-voucher>凭证</button><button class="mini-button" data-refund="${o.orderId}">退款</button>`:''}</div></div>`).join(''):'<div class="empty-state">还没有预约记录。</div>';bindActions()}
function bindActions(){document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=async()=>{await request(`/orders/${b.dataset.pay}/pay`,{method:'POST',body:JSON.stringify({channel:'其他'})});loadOrders()});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await request(`/orders/${b.dataset.cancel}/cancel`,{method:'POST'});loadOrders();loadAvailability()});document.querySelectorAll('[data-refund]').forEach(b=>b.onclick=async()=>{await request(`/orders/${b.dataset.refund}/refund`,{method:'POST'});loadOrders();loadAvailability()});document.querySelectorAll('[data-voucher]').forEach(b=>b.onclick=showVouchers)}
async function showVouchers(){const v=await request('/vouchers');$('#voucherList').innerHTML=v.length?v.map(x=>`<div class="voucher-card"><strong>${x.personName} · ${x.ticketTypeName}</strong><small>${x.visitDate} ${x.slotCode} · ${x.status}</small><small>${x.voucherCode}</small></div>`).join(''):'暂无电子凭证';$('#voucherDialog').showModal()}
async function openBooking(t){if(!needLogin())return;await loadPeople();if(!people.length){$('#personDialog').showModal();return}chosenTicket=t;$('#bookingTicket').innerHTML=`<div class="voucher-card"><strong>${t.name} · ¥${t.price}</strong><small>${selectedDate.toISOString().slice(0,10)} · ${t.slotCode}</small></div>`;$('#bookingPerson').innerHTML=people.map(p=>`<option value="${p.personId}">${p.name} · ${p.idMasked}</option>`).join('');$('#bookingDialog').showModal()}
$('#addPerson').onclick=()=>needLogin()&&$('#personDialog').showModal();$('#personForm').onsubmit=async e=>{e.preventDefault();try{await request('/real-persons',{method:'POST',body:JSON.stringify({name:$('#personName').value,idType:$('#idType').value,idNumber:$('#idNumber').value,isSelf:$('#isSelf').checked})});$('#personDialog').close();e.target.reset();loadPeople()}catch(x){$('#personError').textContent=x.message}};$('#bookingForm').onsubmit=async e=>{e.preventDefault();try{await request('/orders',{method:'POST',body:JSON.stringify({items:[{personId:$('#bookingPerson').value,stockId:chosenTicket.stockId}]})});$('#bookingDialog').close();loadOrders();loadAvailability();location.hash='orders'}catch(x){$('#bookingError').textContent=x.message}};
function openAuth(){if(!$('#authDialog').open)$('#authDialog').showModal();$('#authTitle').textContent=authMode==='login'?'游客登录':'创建游客账号'}$('#loginButton').onclick=()=>token?(localStorage.removeItem('museum_token'),location.reload()):openAuth();$('#switchAuth').onclick=()=>{authMode=authMode==='login'?'register':'login';openAuth()};$('#authForm').onsubmit=async e=>{e.preventDefault();try{const data=await request(`/auth/${authMode}`,{method:'POST',body:JSON.stringify({mobile:$('#mobile').value,password:$('#password').value})});if(authMode==='register'){authMode='login';$('#authError').textContent='注册成功，请登录';return}token=data.token;localStorage.setItem('museum_token',token);$('#authDialog').close();$('#loginButton').textContent='退出登录';loadPeople();loadOrders()}catch(x){$('#authError').textContent=x.message}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#refreshOrders').onclick=loadOrders;$('#prevDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);renderDates();loadAvailability()};$('#nextDate').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);renderDates();loadAvailability()};renderDates();loadAvailability();if(token){$('#loginButton').textContent='退出登录';loadPeople();loadOrders()}
